% Usage: Graphically depict the convergence of optimization methods
% Inputs:
%   x_coordinate:   time or epoch
%   y_coordinate:   cost or optimality_gap or accuracy
%   w:              solution produced algorithms
%   info:           data generated by algorithms
% 
% This file is part of LIBS2ML.
%
% Created by Created by V. K. Chauhan on Sept. 15, 2018
% Modified by V. K. Chauhan on Apr. 14, 2019
function [ fig] = plot_graph(opt, x_coordinates, y_coordinates, algorithm, info, location)
    linewidth = 2;
    linetype = {'ro-','bo-','mo-','go-','co-','yo-','r*-','b*-','m*-','g*-','c*-','y*-','r+--','b+--','m+--','g+--','c+--','y+--','rs:','bs:','ms:','gs:','cs:','ys:','r.','b.','c.','g.','m.','y.'};
    fontsize = 20;
    markersize = 5;
    % initialize
    legend_str = cell(1);
    alg_ind = 0;
    % plot
    fig = figure('position', location);
    for alg_idx=1:length(algorithm)
        if ~isempty(info{alg_idx})
            alg_ind = alg_ind + 1;               
            % selecting y_coordinates
            if strcmp(y_coordinates, 'cost')
                y_data = info{alg_idx}.cost;
            elseif strcmp(y_coordinates, 'accuracy')
                y_data = info{alg_idx}.accuracy;
            elseif strcmp(y_coordinates, 'optimality_gap')
                y_data = info{alg_idx}.cost - opt;
            else                 
            end
            % selecting x_coordinates
            if strcmp(x_coordinates, 'epoch')
                x_data = 0:max(size(y_data))-1;
            elseif strcmp(x_coordinates, 'time')
                x_data = info{alg_idx}.time; 
            else
            end 
            semilogy(x_data, y_data, linetype{alg_ind}, 'MarkerSize', markersize, 'Linewidth', linewidth);
            hold on; 
            legend_str{alg_ind} = algorithm{alg_idx};            
        else
            %
        end
    end
    hold off;
    % select x label
    if strcmp(x_coordinates, 'epoch')
        xlabel('Epochs', 'FontSize', fontsize);
    elseif strcmp(x_coordinates, 'time')
        xlabel('Time (seconds)', 'FontSize', fontsize);   
    else
    end        
    % select y label  
    if strcmp(y_coordinates, 'cost')    
        ylabel('Cost', 'FontSize', fontsize);
    elseif strcmp(y_coordinates, 'accuracy')
        ylabel('Test Accuracy', 'FontSize', fontsize);
    elseif strcmp(y_coordinates, 'optimality_gap')
        ylabel('Optimality gap', 'FontSize', fontsize);
    end
    legend(legend_str);
    set(gca, 'FontSize', fontsize);
end